"""Update ModelSupplier with additional fields from localStorage

Revision ID: 0059f647f0b8
Revises: 
Create Date: 2025-11-24 18:18:04.041748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0059f647f0b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_model_capabilities_id'), 'model_capabilities', ['id'], unique=False)
    op.create_table('model_capability_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['model_capabilities.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_capability_associations_id'), 'model_capability_associations', ['id'], unique=False)
    op.add_column('model_suppliers', sa.Column('api_url', sa.String(length=255), nullable=True))
    op.add_column('model_suppliers', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.add_column('model_suppliers', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('model_suppliers', sa.Column('api_docs', sa.String(length=255), nullable=True))
    op.add_column('model_suppliers', sa.Column('is_domestic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_suppliers', 'is_domestic')
    op.drop_column('model_suppliers', 'api_docs')
    op.drop_column('model_suppliers', 'website')
    op.drop_column('model_suppliers', 'api_key')
    op.drop_column('model_suppliers', 'api_url')
    op.drop_index(op.f('ix_model_capability_associations_id'), table_name='model_capability_associations')
    op.drop_table('model_capability_associations')
    op.drop_index(op.f('ix_model_capabilities_id'), table_name='model_capabilities')
    op.drop_table('model_capabilities')
    # ### end Alembic commands ###