"""Add capability_type column to capabilities table

Revision ID: 3e0fa44cc839
Revises: 0059f647f0b8
Create Date: 2025-11-28 06:52:09.108611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3e0fa44cc839'
down_revision = '0059f647f0b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_suppliers_id', table_name='model_suppliers')
    op.drop_table('model_suppliers')
    op.drop_index('ix_models_id', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_model_configurations_id', table_name='model_configurations')
    op.drop_table('model_configurations')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_llm_request_history_id', table_name='llm_request_history')
    op.drop_table('llm_request_history')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_model_capabilities_id', table_name='model_capabilities')
    op.drop_table('model_capabilities')
    op.drop_index('ix_model_capability_associations_id', table_name='model_capability_associations')
    op.drop_table('model_capability_associations')
    op.add_column('capabilities', sa.Column('capability_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilities', 'capability_type')
    op.create_table('model_capability_associations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('capability_id', sa.INTEGER(), nullable=False),
    sa.Column('config', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['model_capabilities.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_capability_associations_id', 'model_capability_associations', ['id'], unique=False)
    op.create_table('model_capabilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('capability_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_model_capabilities_id', 'model_capabilities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('llm_request_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('request_params', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_request_history_id', 'llm_request_history', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('token_count', sa.INTEGER(), nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), nullable=True),
    sa.Column('response_time', sa.INTEGER(), nullable=True),
    sa.Column('is_streaming', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('model_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('api_key_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('default_temperature', sa.FLOAT(), nullable=True),
    sa.Column('default_max_tokens', sa.INTEGER(), nullable=True),
    sa.Column('default_top_p', sa.FLOAT(), nullable=True),
    sa.Column('default_frequency_penalty', sa.FLOAT(), nullable=True),
    sa.Column('default_presence_penalty', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index('ix_model_configurations_id', 'model_configurations', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('context_window', sa.INTEGER(), nullable=True),
    sa.Column('default_temperature', sa.FLOAT(), nullable=True),
    sa.Column('default_max_tokens', sa.INTEGER(), nullable=True),
    sa.Column('default_top_p', sa.FLOAT(), nullable=True),
    sa.Column('default_frequency_penalty', sa.FLOAT(), nullable=True),
    sa.Column('default_presence_penalty', sa.FLOAT(), nullable=True),
    sa.Column('custom_params', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['model_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_models_id', 'models', ['id'], unique=False)
    op.create_table('model_suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('api_key_env_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('api_docs', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_domestic', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_model_suppliers_id', 'model_suppliers', ['id'], unique=False)
    # ### end Alembic commands ###